sudo: required
services:
  - docker

before_install:
  - docker build -t shulogna29/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shulogna29/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SWECRET_KEY"