sudo: required
services:
  - docker

before_install:
  - docker build -t shulogna29/Docker -f Dockerfile .

script:
  - docker run -e CI=true shulogna29/Docker npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "Docker"
  env: "Docker-env"
  bucket_name: "Docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SWECRET_KEY"